[package]
name = "fbaas-rust"
version = "0.1.0"
authors = ["Chad McElligott <chad@chadxz.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "*"
serde_json = "*"
tokio = "*"