AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FizzBuzz as a Service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Domain:
      DomainName: fbaas.cloud.chadxz.dev
      CertificateArn: arn:aws:acm:us-east-1:586284076313:certificate/1d096fdd-e908-4341-b026-3b40f17769b7
      EndpointConfiguration: EDGE
      Route53:
        HostedZoneId: Z07956462RTGJHGZI327V
Resources:
  FizzBuzzFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: provided
      Runtime: provided.al2
      Events:
        IncomingApiRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FbaasApi:
    Description: "API Gateway endpoint URL for Prod stage for FizzBuzz function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  FizzBuzzFunction:
    Description: "FizzBuzz Lambda Function ARN"
    Value: !GetAtt FizzBuzzFunction.Arn
  FizzBuzzFunctionIamRole:
    Description: "Implicit IAM Role created for FizzBuzz function"
    Value: !GetAtt FizzBuzzFunctionRole.Arn
