AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FizzBuzz as a Service
Parameters:
  ApiDomainName:
    Type: String
    Default: fbaas.cloud.chadxz.dev
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Domain:
      DomainName: !Ref ApiDomainName
      CertificateArn: arn:aws:acm:us-east-1:586284076313:certificate/1d096fdd-e908-4341-b026-3b40f17769b7
      EndpointConfiguration: EDGE
      Route53:
        HostedZoneId: Z07956462RTGJHGZI327V
Resources:
  FizzBuzzFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: provided
      Runtime: provided.al2
      Events:
        IncomingApiRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{number}
            Method: get
Outputs:
  ApplicationUrl:
    Description: "API Gateway endpoint URL for the application"
    Value: !Sub "https://${ApiDomainName}/"