name: Deployment Preview
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2 # add CI_ env vars
      - run: echo "ENVIRONMENT_NAME=branch-${{ env.CI_HEAD_REF_SLUG }}" >> $GITHUB_ENV
      - run: echo "APP_NAME=fbaas-${{ env.ENVIRONMENT_NAME }}" >> $GITHUB_ENV
      - run: echo "API_DOMAIN_NAME=${{ env.APP_NAME }}.cloud.chadxz.dev" >> $GITHUB_ENV
      - run: echo "APPLICATION_URL=https://${{ env.API_DOMAIN_NAME }}" >> $GITHUB_ENV

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.6.0
        if: ${{ !env.ACT }}
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.ENVIRONMENT_NAME }}
          ref: ${{ github.head_ref }}
          transient: true
          no_override: false

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: sam build
      - run: |
          sam deploy --no-confirm-changeset \
                     --no-fail-on-empty-changeset \
                     --stack-name="${{ env.APP_NAME }}" \
                     --s3-bucket="aws-sam-cli-managed-default-samclisourcebucket-19gvdka7u74px" \
                     --s3-prefix="${{ env.APP_NAME }}" \
                     --region="us-east-1" \
                     --parameter-overrides "ApiDomainName=${{ env.API_DOMAIN_NAME }}"\
                     --capabilities="CAPABILITY_IAM"

      - name: Seal Deployment
        uses: bobheadxi/deployments@v0.5.2
        if: ${{ always() && !env.ACT }}
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ env.APPLICATION_URL }}